// ============================================================
// AquaSphere — PDF Generator  (Modern Clean Design)
// js/pdf.js  (jsPDF loaded globally via CDN script tag)
// ============================================================

function makePDF(titleRaw, content) {
  var jsPDF = window.jspdf ? window.jspdf.jsPDF : window.jsPDF;
  if (!jsPDF) { toast('PDF library not loaded','error'); return; }
  var doc = new jsPDF({ orientation:'portrait', unit:'mm', format:'a4' });
  var W   = doc.internal.pageSize.getWidth();
  var H   = doc.internal.pageSize.getHeight();
  var title = titleRaw.replace(/_/g,' ');
  var pageNum = 1;

  function drawPage() {
    // White bg
    doc.setFillColor(255,255,255);
    doc.rect(0,0,W,H,'F');
    // Top accent bar
    doc.setFillColor(0,140,190);
    doc.rect(0,0,W,7,'F');
    // Sub-bar
    doc.setFillColor(0,212,255);
    doc.rect(0,7,W,2,'F');
    // Header bg
    doc.setFillColor(247,251,255);
    doc.rect(0,9,W,24,'F');
    // Header bottom border
    doc.setDrawColor(210,228,242);
    doc.setLineWidth(0.3);
    doc.line(0,33,W,33);

    // Org name
    doc.setTextColor(0,120,170);
    doc.setFontSize(13);
    doc.setFont('helvetica','bold');
    doc.text('AQUASPHERE', 13,19);
    doc.setFontSize(7.5);
    doc.setFont('helvetica','normal');
    doc.setTextColor(100,130,155);
    doc.text('DIVING CENTER', 13,26);

    // Document title
    doc.setTextColor(25,45,70);
    doc.setFontSize(11);
    doc.setFont('helvetica','bold');
    doc.text(title, W-12, 19, {align:'right'});

    // Date + page
    doc.setFontSize(8);
    doc.setFont('helvetica','normal');
    doc.setTextColor(110,135,160);
    var dateStr = new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});
    doc.text(dateStr + '  ·  Page ' + pageNum, W-12, 27, {align:'right'});

    // Footer
    doc.setFillColor(247,251,255);
    doc.rect(0, H-13, W, 13, 'F');
    doc.setDrawColor(210,228,242);
    doc.line(0, H-13, W, H-13);
    doc.setFontSize(7.5);
    doc.setTextColor(130,155,175);
    doc.setFont('helvetica','normal');
    doc.text('AquaSphere Diving Center  ·  Confidential Record', 12, H-5);
    doc.text('Generated by AquaSphere Management System', W-12, H-5, {align:'right'});
  }

  drawPage();
  var y = 42;

  function chkSpc(n) {
    if (y + n > H-18) { doc.addPage(); pageNum++; drawPage(); y = 42; }
  }

  function renderBlock(b) {
    if (!b) return;
    switch(b.type) {

      case 'section':
        chkSpc(13);
        doc.setFillColor(230,245,252);
        doc.roundedRect(8, y-4, W-16, 10, 1.5, 1.5, 'F');
        doc.setFillColor(0,160,215);
        doc.rect(8, y-4, 3, 10, 'F');
        doc.setFontSize(9); doc.setFont('helvetica','bold');
        doc.setTextColor(0,100,155);
        doc.text(b.text, 15, y+2.8);
        y += 13;
        break;

      case 'row':
        chkSpc(8);
        doc.setFontSize(8.5); doc.setFont('helvetica','bold');
        doc.setTextColor(80,105,130);
        doc.text(String(b.label||'')+':',  12, y);
        doc.setFont('helvetica','normal');
        doc.setTextColor(25,45,70);
        var vLines = doc.splitTextToSize(String(b.value||'—'), W-75);
        doc.text(vLines, 65, y);
        y += vLines.length * 5.5 + 2;
        break;

      case 'check':
        chkSpc(8);
        // box
        doc.setLineWidth(0.5);
        if (b.checked) {
          doc.setFillColor(22,163,74); doc.setDrawColor(22,163,74);
          doc.roundedRect(11,y-3.5,5,5,1,1,'FD');
          doc.setTextColor(255,255,255); doc.setFontSize(7); doc.setFont('helvetica','bold');
          doc.text('✓',12.5,y+0.2);
        } else {
          doc.setFillColor(248,250,252); doc.setDrawColor(180,200,220);
          doc.roundedRect(11,y-3.5,5,5,1,1,'FD');
          doc.setTextColor(185,200,215); doc.setFontSize(7); doc.setFont('helvetica','normal');
          doc.text('✕',12.5,y+0.2);
        }
        doc.setFontSize(8.5); doc.setFont('helvetica','normal');
        doc.setTextColor(b.checked ? 25:100, b.checked ? 45:115, b.checked ? 70:135);
        var cLines = doc.splitTextToSize(b.text||'', W-36);
        doc.text(cLines, 21, y);
        y += cLines.length * 5.2 + 1.5;
        break;

      case 'text':
        chkSpc(8);
        doc.setFontSize(8.5);
        doc.setFont('helvetica', b.bold ? 'bold':'normal');
        doc.setTextColor(b.bold ? 25:90, b.bold ? 45:110, b.bold ? 70:130);
        var tLines = doc.splitTextToSize(b.text||'', W-24);
        chkSpc(tLines.length * 5.5 + 3);
        doc.text(tLines, 12, y);
        y += tLines.length * 5.5 + 3;
        break;

      case 'divider':
        chkSpc(8);
        doc.setDrawColor(215,230,242); doc.setLineWidth(0.3);
        doc.line(12, y, W-12, y);
        y += 8;
        break;

      case 'spacer':
        y += (b.h || 6);
        break;

      case 'kv':
        var pairs = b.pairs || [];
        var half  = Math.ceil(pairs.length / 2);
        chkSpc(Math.ceil(pairs.length / 2) * 7 + 4);
        for (var pi = 0; pi < half; pi++) {
          var lp = pairs[pi];
          var rp = pairs[pi + half];
          doc.setFontSize(8); doc.setFont('helvetica','bold'); doc.setTextColor(80,105,130);
          doc.text(String(lp.label||'')+':',  12, y);
          doc.setFont('helvetica','normal');  doc.setTextColor(25,45,70);
          doc.text(String(lp.value||'—'), 44, y);
          if (rp) {
            doc.setFont('helvetica','bold');  doc.setTextColor(80,105,130);
            doc.text(String(rp.label||'')+':',  W/2+4, y);
            doc.setFont('helvetica','normal'); doc.setTextColor(25,45,70);
            doc.text(String(rp.value||'—'),  W/2+36, y);
          }
          y += 7;
        }
        y += 2;
        break;

      case 'table':
        var cols = b.cols || [];
        var rows = b.rows || [];
        var cw   = (W-24) / cols.length;
        chkSpc(11);
        // Header
        doc.setFillColor(0,140,190);
        doc.rect(12, y-3, W-24, 9, 'F');
        doc.setFontSize(8); doc.setFont('helvetica','bold'); doc.setTextColor(255,255,255);
        cols.forEach(function(c,ci) { doc.text(String(c), 14+ci*cw, y+2.5); });
        y += 10;
        // Rows
        rows.forEach(function(row, ri) {
          chkSpc(8);
          if (ri%2===0) { doc.setFillColor(246,251,255); doc.rect(12,y-3,W-24,8,'F'); }
          doc.setFontSize(8); doc.setFont('helvetica','normal'); doc.setTextColor(30,50,70);
          row.forEach(function(cell,ci) {
            var cellLines = doc.splitTextToSize(String(cell||'—'), cw-3);
            doc.text(cellLines[0], 14+ci*cw, y+1.5);
          });
          y += 8;
        });
        y += 3;
        break;
    }
  }

  content.forEach(renderBlock);

  // page numbers on all pages
  var total = doc.internal.getNumberOfPages();
  for (var p = 1; p <= total; p++) {
    doc.setPage(p);
    doc.setFontSize(7.5); doc.setFont('helvetica','normal');
    doc.setTextColor(130,155,175);
    doc.text('Page ' + p + ' of ' + total, W-12, H-5, {align:'right'});
  }

  doc.save(titleRaw + '_' + Date.now() + '.pdf');
}

// ── Checklist-specific PDF helper ────────────────────────────
function generateChecklistPDF(type) {
  var isOW   = type === 'ow';
  var prefix = isOW ? 'ow' : 'pool';
  var $v     = function(id) { var el=document.getElementById(id); return el ? (el.value||'—') : '—'; };
  var $chk   = function(id) { var el=document.getElementById(id); return el ? el.checked : false; };
  var $selTxt= function(id) { var el=document.getElementById(id); return el && el.options ? (el.options[el.selectedIndex]||{text:'N/A'}).text : 'N/A'; };

  var divers = DB.get('divers');
  var users  = DB.get('users');
  var diver  = divers.find(function(d){ return d.id == $v(prefix+(isOW?'-diver':'-student')); });
  var inst   = users.find(function(u){ return u.id == $v(prefix+'-instructor'); });

  var content = [
    {type:'section', text: isOW?'PRE-DIVE CHECKLIST — OPEN WATER SESSION':'PRE-DIVE CHECKLIST — POOL / CONFINED WATER'},
    {type:'spacer',h:2},
    {type:'kv', pairs:[
      {label: isOW?'Diver Name':'Student Name', value: diver?diver.name:'N/A'},
      {label:'Instructor',   value: inst?inst.name:'N/A'},
      {label:'Date',         value: $v(prefix+'-date')},
      {label: isOW?'Dive Site':'Pool',
       value: isOW ? $selTxt('ow-site') : $v('pool-name')},
      {label:'Session Type', value: $v(isOW?'ow-plan':'pool-type')},
      {label:'Time',         value: isOW ? $v('ow-time') : '—'}
    ]},
    {type:'divider'},
    {type:'section', text:'A. Health Check'},
  ].concat(
    (isOW
      ? ['Feeling well (no cold/fatigue)','No alcohol or drugs in 12h','No recent injuries','Medical form completed','Diver hydrated']
      : ['Student feels well','No breathing issues','No open wounds','No recent injuries','Medical form completed']
    ).map(function(t,i){ return {type:'check', text:t, checked:$chk(prefix+'-a'+i)}; }),
    [{type:'divider'},{type:'section',text:'B. Equipment Check'}],
    (isOW
      ? ['Wetsuit/Drysuit appropriate','Gloves / hood if needed','Mask, snorkel, fins OK','Weights checked']
      : ['Mask fits and clear','Fins correct size','Boots if required']
    ).map(function(t,i){ return {type:'check', text:t, checked:$chk(prefix+'-b'+i)}; }),
    (isOW
      ? ['Cylinder + O-ring OK','Regulator (primary + alt)','BCD inflates/deflates','LPI working','Computer functioning','Leak test done']
      : ['Tank valve OK','Regulator functioning','BCD inflates/deflates','LPI working','Weight system OK','Leak test done']
    ).map(function(t,i){ return {type:'check', text:t, checked:$chk(prefix+'-b2'+i)}; }),
    [{type:'kv', pairs:[
      {label:'Starting Pressure', value:$v(prefix+'-press-start')+' bar'},
      {label:'Ending Pressure',   value:$v(prefix+'-press-end')+' bar'}
    ]},{type:'divider'},
    {type:'section', text: isOW?'C. Site & Environment':'C. Pool Safety'}],
    (isOW
      ? ['Weather acceptable','Entry/exit briefed','Marine hazards explained','Surface support in place','Emergency O2 ready']
      : ['Pool depth confirmed','Slippery surfaces briefed','Emergency exit shown','First Aid available','Emergency O2 available']
    ).map(function(t,i){ return {type:'check', text:t, checked:$chk(prefix+'-c'+i)}; }),
    isOW ? [
      {type:'kv', pairs:[
        {label:'Current',    value:$v('ow-current')},
        {label:'Visibility', value:$v('ow-vis')+' m'},
        {label:'Max Depth',  value:$v('ow-depth')+' m'},
        {label:'Bottom Time',value:$v('ow-bt')+' min'}
      ]},
      {type:'row', label:'Skills Planned', value:$v('ow-skills')},
      {type:'divider'},
      {type:'section', text:'D. Dive Plan'},
    ].concat(
      ['Signals reviewed','Lost buddy procedure','Neutral buoyancy check','SMB / surfacing plan']
        .map(function(t,i){ return {type:'check', text:t, checked:$chk('ow-d'+i)}; })
    ) : [
      {type:'divider'},{type:'section',text:'D. Session Plan'}
    ].concat(
      ['Equipment handling','Breathing underwater','Buoyancy basics','Regulator recovery','Mask skills','Signals / safety']
        .map(function(t,i){ return {type:'check', text:t, checked:$chk('pool-d'+i)}; })
    ),
    [{type:'divider'},{type:'section',text:'E. Final BWRAF Check'}],
    ['B – BCD','W – Weights','R – Releases','A – Air','F – Final OK']
      .map(function(t,i){ return {type:'check', text:t, checked:$chk((isOW?'ow':'pool')+'-e'+i)}; }),
    [{type:'divider'},{type:'section',text:'Sign-Off'}],
    [{type:'kv', pairs:[
      {label: isOW?'Diver Signature':'Student Signature',
       value: $v(prefix+'-sig-'+(isOW?'diver':'student'))||'Not signed'},
      {label:'Instructor Signature', value: $v(prefix+'-sig-inst')||'Not signed'}
    ]}],
    [{type:'spacer',h:5},
     {type:'text', text:'This is a legally binding pre-dive safety record. Retain for a minimum of 3 years.', bold:false}]
  );

  makePDF(isOW?'OW_PreDive_Checklist':'Pool_PreDive_Checklist', content);
  if (window.currentUser) {
    DB.log(currentUser.id, currentUser.name, 'Generate PDF', (isOW?'OW':'Pool')+' checklist');
  }
  toast('PDF generated!','success');
}
